default:
  target: dev
  outputs:
    dev:
      type: databricks
      schema: default
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "/sql/1.0/endpoints/652e6128a92eb5c5"
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
